import { DayOfWeek, DateRangeType } from "office-ui-fabric-react/lib/Calendar";

 const init={
    test:"sdfa",
    username:"JhonSnow",
    password:123456789,
    uservalid:false,
    number:0,
    valid:false,
    posts:[],
    isMonthPickerVisible: false,
    dateRangeType: DateRangeType.Day,
    autoNavigateOnSelection: true,
    showGoToToday: true,
    navigationIcons:{leftNavigation:'ChevronLeft'},
    showNavigateButtons: false,
    highlightCurrentMonth: false,
    highlightSelectedMonth: true,
    isDayPickerVisible: false,
    showMonthPickerAsOverlay: true,
    showWeekNumbers: true,
    showCloseButton:true,
    restrictedDates: [],
    showSixWeeksByDefault: true,
    workWeekDays: [],
    firstDayOfWeek: DayOfWeek,
    customerList:[{address: "15548 se 5th ct bellevue",
                    bod: "4/30/2019",
                    cellphone: " (454) 349 - 4568",
                    contry: "China",
                    countryState: "Beijng",
                    firstName: "molly",
                    gender: "Female",
                    lastName: "zxczx",
                    password: "12345678",
                    userName: "mike",
                    zipcode: "98007",
                    admin:true
                
                },

                    {address: "677 NE 148th ct Kirland",
                    bod: "5/6/2001",
                    cellphone: " (434) 123 - 63176",
                    contry: "China",
                    countryState: "Shanxi",
                    firstName: "bfgh",
                    gender: "Male",
                    lastName: "xcvw",
                    password: "asdfxcv",
                    userName: "cvbrt",
                    zipcode: "98005",
                    admin:false},

                    {address: "677 NE 148th ct Kirland",
                    bod: "5/6/2001",
                    cellphone: " (434) 123 - 63176",
                    contry: "United States",
                    countryState: "OH",
                    firstName: "bfgh",
                    gender: "Male",
                    lastName: "xcvw",
                    password: "asdfxcv",
                    userName: "xfgnbfgh",
                    zipcode: "98005",
                    admin:false},

                    {address: "677 NE 148th ct Kirland",
                    bod: "5/6/2001",
                    cellphone: " (434) 123 - 63176",
                    contry: "United States",
                    countryState: "OR",
                    firstName: "bfgh",
                    gender: "Male",
                    lastName: "xcvw",
                    password: "asdfxcv",
                    userName: "werwer",
                    zipcode: "98005",
                    admin:false},

                    {address: "677 NE 148th ct Kirland",
                    bod: "5/6/2001",
                    cellphone: " (434) 123 - 63176",
                    contry: "United States",
                    countryState: "OR",
                    firstName: "john",
                    gender: "Male",
                    lastName: "snow",
                    password: "123456789",
                    userName: "john",
                    zipcode: "98005",
                    admin:true}
                
                
                ],
    customerListShow:[],
    serchitem:"",
    currentUser:"",
    

}
export default init;